### ISSUE TITLE
Rice powerline 

### ISSUE THREAD

**Issue by t-monaghan** [t-monaghan/nixfiles#9]
Ideas:
- Match gruvbox theme
- Collapse ran commands to just the working folder name (UEW collapses all, Gruvbox no collapse)
- Collapse git plugin when outside of git (gruvbox does this)

**Comment by tmonaghan-rmit** [comment]
- Remove OS
 - Remove triangles/bg?
 - Put a symbol in front of command

**Comment by t-monaghan** [comment]
- Have any directory/project specific segments collapse when not relevant

**Comment by t-monaghan** [comment]
Chuck nerdfont line connector between newlines on leftside
